---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Niki Zakariassen.
--- DateTime: 26-04-2022 22:34
---

function new (event)
    local self = {
        --- @type table
        event = event,
    }

    --- Define public API
    --- @class MonitorTouchEvent
    local public = {
        name = event[1],
        direction = event[2],
        x = event[3],
        y = event[4],
    }

    --- Make it possible to access public/private api from self
    return setmetatable(self, {__index = public})
end

return {new = new}