---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Niki Zakariassen.
--- DateTime: 26-04-2022 22:34
---

EnhancedMonitor = {monitor = nil}

function EnhancedMonitor.setMonitor (monitor)
    EnhancedMonitor.monitor = monitor
end

function EnhancedMonitor.helloWorld ()
    EnhancedMonitor.monitor.write("Hello World!")
end