---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Niki Zakariassen.
--- DateTime: 26-04-2022 22:34
---

function EnhancedMonitor:new ()
    o = {
        monitor = nil
    }
    setmetatable(o, self)
    self.__index = self
    return o
end

function EnhancedMonitor:setMonitor(monitor)
    self.monitor = monitor
end

function EnhancedMonitor:helloWorld()
    self.monitor.write("Hello World")
end