---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Niki Zakariassen.
--- DateTime: 26-04-2022 22:34
---

function new (direction)
    local self = {
        terminal = peripheral.wrap(direction),
    }

    --- Pass any unknown function calls to the underlying terminal
    setmetatable(self, self.terminal)

    --- Define public API
    return {
        setMonitor = function (terminal)
            self.terminal = terminal
        end,

        helloWorld = function ()
            self.terminal.write("Hello World!")
        end,

        clear = function ()
            self.terminal.clear()
            self.terminal.setCursorPos(1,1)
        end
    }
end

return {new = new}