---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Niki Zakariassen.
--- DateTime: 26-04-2022 22:34
---

function new ()
    local self = {
        monitor = nil
    }

    return {
        setMonitor = function (monitor)
            self.monitor = monitor
        end,

        helloWorld = function ()
            self.monitor.write("Hello World!")
        end,

        clear = function ()
            self.monitor.clear()
            self.monitor.setCursorPos()
        end
    }
end