---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Niki Zakariassen.
--- DateTime: 26-04-2022 22:34
---

Serializer = {}

function Serializer.save(data, fileName)
    local file = fs.open(fileName, "w")

    file.write(textutils.serialize(data))
    file.close()
end

function Serializer.load(fileName)
    local file = fs.open(fileName, "r")
    local data = file.readAll()
    file.close()

    return textutils.unserialize(data)
end